### ISSUE TITLE
Add documentation for Actions on Google Unit testing with bst

### ISSUE THREAD

**Issue by jperata** [bespoken/bespoken-docs#12]
**Description:**
We do not document how users can test google actions.

**Environment:**
All versions

**Steps To Reproduce**
Look at the docs, see there is no reference to  how users can test google actions.

**Expected behavior**

Under the configuration section for both unit-testing, there should be a section that explains how to test google actions. It should be titled: "Actions on Google Testing". The section should:

    Explain how to setup a google action skill before doing testing
    Provide an example of a simple unit test for google
    Include an advanced section indicating the different ways to start the handler (from server, from action class).

**Comment by MKen-li** [comment]
Marked as verified
