### ISSUE TITLE
Images are broken when clicked on

### ISSUE THREAD

**Issue by jkelvie** [bespoken/bespoken-docs#146]
Some of our images in the docs are broken if you click on them. For example this, image:
![image](https://user-images.githubusercontent.com/17267/89800345-47d15d00-daf4-11ea-962e-f3cbea753280.png)

When you click on it, you get this:
![image](https://user-images.githubusercontent.com/17267/89800379-53248880-daf4-11ea-8bed-8ac97bf489b0.png)

The image can be found in this section:
https://read.bespoken.io/end-to-end/faq/#how-do-i-change-my-virtual-device-location-to-test-location-specific-features

It seems that the problem is images need to be defined explicitly at the bottom of the markdown file in VuePress:
https://raw.githubusercontent.com/bespoken/bespoken-docs/gh-pages/end-to-end/faq.md?token=AAAEG4ZESLJ4NFZX57CJSNC7GFUOK

If you jump to the bottom of the file, you will see references images are defined.

Ideally, it would NOT be necessary to do this - the images show fine inline - it is only when they are clicked on that they break. This seems like a gotcha that will keep happening. So if we can change the configuration of VuePress to make images automatically clickable, that would be preferred. If not possible, we should make sure to include them at the bottom of the file.

**Comment by dmarvp** [comment]
Verified.
