### ISSUE TITLE
Update shorthands documentation

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bespoken-docs#16]
From: 
https://github.com/bespoken/skill-testing-ml/issues/146
and
https://github.com/bespoken/skill-testing-ml/issues/132

In:
https://read.bespoken.io/end-to-end/guide/#shorthand-properties

We need to update the list of shorthands that we have. Specify that we now support "card" as well and the properties that we do not support for google: card.type and streamURL.

**Comment by MKen-li** [comment]
Marked as verified
