### ISSUE TITLE
update faq regarding parallel requests with the same account

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bespoken-docs#17]
As of now, virtual devices tied to the same Amazon account (we need to test this with Google as well) don't seem to work if used in parallel. Update the FAQ to explain this and give the alternative that is using multiple amazon accounts with virtual devices.

**Comment by dmarvp** [comment]
Please test it with Google too and include that in the faq if needed.

**Comment by jperata** [comment]
Did a couple of tests with google, parallel tests seems to work even when using the same token

**Comment by MKen-li** [comment]
Marked as verified
