### ISSUE TITLE
migrate CLI tutorials for node-js, python and java

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bespoken-docs#21]
### Summary 
In read.bespoken.io, under CLI and Tutorials we have links for 
- Node Js and Lambda: points to http://docs.bespoken.io/en/latest/tutorials/tutorial_lambda_nodejs/
- Python and Flask: points to http://docs.bespoken.io/en/latest/tutorials/tutorial_flask_ask_python/
- Local Java Server: points to http://docs.bespoken.io/en/latest/tutorials/tutorial_local_server_java/

However, under https://read.bespoken.io/cli/commands/
We link to:
- http://read.bespoken.io/en/latest/tutorials/tutorial_lambda_nodejs/
- http://read.bespoken.io/en/latest/tutorials/tutorial_lambda_nodejs/
- http://read.bespoken.io/en/latest/tutorials/tutorial_lambda_nodejs/
which don't exist, therefore they are broken links

We could either:
- Point those links to docs.bespoken.io
- Migrate those articles to read.bespoken.io, and change the links on the main page of read.bespoken.io

I think we should do the second one, since we are moving away from docs.bespoken.io

**Comment by MKen-li** [comment]
Marked as verified
