### ISSUE TITLE
Add documentation for Google's virtual devices additional steps.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bespoken-docs#36]
here: https://read.bespoken.io/end-to-end/setup/#virtual-devices-for-google

There should be an additional note to include these steps whenever something like this happens:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/6411740/57892617-2dcba080-7805-11e9-9984-ec7e97195837.png">

1. Long press the “home” button on an Android device.
2. Click on the compass icon. 
3. Click on your user's icon.
4. Click on Settings
5. Click on the Assistant Tab
6. Scroll Down and you should see “virtual device” listed after your phone.
7. Click on it and enable Personal Results.

Please add screenshots or a gif on how to do it as well as the text for it.
We should also add it as an FAQ (with a link to this steps) here: https://read.bespoken.io/end-to-end/faq/

**Comment by MKen-li** [comment]
Marked as blocked
waiting for https://github.com/bespoken/bespoken-docs/issues/37

**Comment by MKen-li** [comment]
Marked as verified
