### ISSUE TITLE
Migrate the docs to VuePress

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bespoken-docs#37]
### Description
We currently deploy our docs to GitHub-pages using a Jekyll Theme. We want to make use of the same markdown files we use for this but leave Jekyll behind in favor of VuePress.

You can read more about Vuepress here: https://vuepress.vuejs.org

The first step would be to run VuePress locally and load our docs on another branch. After that, deploy these to Github Pages and replace our current docs site. 

### Reference links
VuePress on how to deploy to Github Pages: https://vuepress.vuejs.org/guide/deploy.html
A project that might help to achieve this: https://github.com/scriptex/github-pages-vuepress

**Comment by daisyzarzo** [comment]
here is where deployed the Bespoken documentation
https://5cf701b7c7f36d00088baec5--zen-pike-2b04c4.netlify.com/

**Comment by MKen-li** [comment]
Marked as verified
