### ISSUE TITLE
Rename the FAQ sections so that they don't mix in the search bar

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bespoken-docs#67]
### Summary
If you search for FAQ in the docs search bar, this is what you get:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/6411740/64300429-fa13b280-cf7c-11e9-92fa-d7961e3245de.png">

One of them belongs to Unit Testing and the other to End to End Testing. We should change it so that it reflects:

- FAQ (Unit Testing)
- FAQ (End to End Testing)

**Comment by MKen-li** [comment]
Marked as verified
