### ISSUE TITLE
Update content and images on "Creating a Virtual Device" page

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bespoken-docs#76]
### Summary
The following page: https://read.bespoken.io/end-to-end/setup/#background has outdated content and images. Please update them by:

- Describing how to create a virtual device by using the **virtual device manager**.
- Updating the images on the page with the new Dashboard design.

**Comment by MKen-li** [comment]
Marked as verified

**Comment by MKen-li** [comment]
Re-open ticket,
The images in the steps don't have a border and are not in the correct resolution

**Comment by dmarvp** [comment]
More than that, it seems as we had used screenshots of a minified window. We can just do screenshots or gifs of the buttons or parts we are mentioning. We don't need to do the whole window everytime, specially if it breaks the design. ie:

![image](https://user-images.githubusercontent.com/6411740/67130925-76c6bd00-f1c8-11e9-913f-3bc0f931364f.png)

should be:

![image](https://user-images.githubusercontent.com/6411740/67130963-91993180-f1c8-11e9-8327-cbcc86a7084d.png)

or even better:

![Oct-18-2019 17-02-41](https://user-images.githubusercontent.com/6411740/67131139-2734c100-f1c9-11e9-9611-f78c2391dc58.gif)

**Comment by jricaldi** [comment]
with gif images https://5db740809bea700008d4ebd1--zen-pike-2b04c4.netlify.com/end-to-end/setup/#creating-a-virtual-device
