### ISSUE TITLE
documentation should support URL with or without HTML

### ISSUE THREAD

**Issue by MKen-li** [bespoken/bespoken-docs#81]
https://read.bespoken.io/tutorials/tutorial-lambda-nodejs.html is not working and is sent by Google search

https://read.bespoken.io/tutorials/tutorial-lambda-nodejs/ This URL is working correctly

**Comment by jkelvie** [comment]
Is that just for this one specific URL? Or do you mean for all the URLs?

**Comment by MKen-li** [comment]
Good question, this issue is mainly because a user doing a google search of "Debugging your Node voice apps locally Bespoken"is being sent to the URL with html. So he gets a 404 error we could 1 make all URL's accept the html or we could just wait for google to update the data @dmarvp @jperata

**Comment by MKen-li** [comment]
Also looking at the issue closer we have an example where we do a redirect correctly like:
https://read.bespoken.io/end-to-end/guide/
https://read.bespoken.io/end-to-end/guide.html
Both URL sent you to the correct information

**Comment by MKen-li** [comment]
Marked as verified
